//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interview_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        
        
        public int C_Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string C_Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Invalid input.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> Date { get; set; }

        [Required(ErrorMessage = "Required")]
        public string College_Name { get; set; }

        [Required(ErrorMessage = "Required")]

        [DisplayName("Qualification")]
        public string Higher_Qualification { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Stream { get; set; }

        [Required(ErrorMessage = "Required")]
        public string YearOfPassing { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Percentage { get; set; }

        
        public byte[] ResumeFile { get; set; }

        
        public string FileName { get; set; }

        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
