//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interview_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int F_Id { get; set; }

        [Required (ErrorMessage = "Required")]
        public Nullable<System.DateTime> Date { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Screening_Level { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> Candidate_Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> Interviwer_Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Feedback1 { get; set; }
        public string Result { get; set; }

        
        public string Interviwer_Name { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual Interviwer Interviwer { get; set; }
        
       
    }
}
